### PR TITLE
Added `Send(ArraySegment<byte>)` methods for server and client

### PR DESCRIPTION
**Pull request by martindevans**
Added Send methods for both client and server which accept an array segment. This allows packets to be written into large preallocated buffers and then sent without any run time allocations (otherwise you need to allocate a buffer of exactly the right size to specify the length to Ignorance).

### CODE REVIEW

**Comment by martindevans** [comment]
See [this issue](https://github.com/vis2k/Mirror/issues/400) on Mirror for related discussion to this PR.

**Comment by SoftwareGuy** [comment]
I think it will be best if I labelled this as Experimental until we see what the upstream guys do with it. I won't reject it, but I am curious to see what it does differently. So I will take a looksie and step through the code.

**Comment by martindevans** [comment]
The main problem I was having was that when trying to send packets Mirror allocates like crazy and has an API that forces me to allocate too (e.g. creating a byte array of exactly the right size for every packet). The idea of this PR is that I could pass in an `ArraySegment<byte>` and save myself allocating those exact size buffers, I would then go through Mirror and add similar APIs which allow accessing this independently of the backend (as proposed in [Mirror#400](https://github.com/vis2k/Mirror/issues/400)).

These methods on Ignorance would still be _usable_ without those changes to Mirror but they're not nearly as useful if I can't add a transport-independent way to use them. I'll discuss some more over on that Mirror issue to see if we can work out a way to get them added.

**Comment by SoftwareGuy** [comment]
Alright, I'll merge this but I'll blame you if it crashes Ignorance. 😛 

I am also probably going to overhaul both the client and server routines to use a memory buffer (probably default to 32KB, configurable) as per what nxrighthere suggests in #17 to avoid memory allocations on the stack.

Consider it accepted, but expect bug reports if it doesn't work! 😄

**Comment by martindevans** [comment]
Thanks for merging this. Unfortunately the corresponding PR in Mirror was rejected so there won't be a transport agnostic way of using these methods :(

**Comment by paulpach** [comment]
@martindevans it is easy to reopen a PR,  but we need to see numbers.

**Comment by SoftwareGuy** [comment]
@martindevans Fear not. I might get in touch with you regarding this as I think it might help us when we're dealing with memory copying. I want to improve the packet data handling in Ignorance 1.2 and avoid allocating new buffers on the stack, but I'm not sure if I'm doing it in the correct way - if you know of a zero allocation way, then I'm all ears.

**Comment by martindevans** [comment]
@SoftwareGuy I'll be happy to help out with that. From what I remember otoh Ignorance already doesn't allocate much, so I think we can drive it to zero without too much effort :)

**Comment by martindevans** [comment]
I had a look through all the allocations in `IgnoranceTransport.cs` in more detail and I think there are really only two worth worrying about:

`byte[] data = new byte[incomingEvent.Packet.Length];` Line 338 (server receive)
`byte[] data = new byte[incomingEvent.Packet.Length];` Line 600 (client receive)

These are both doing the same thing; providing a destination for received packets to be copied into.

Unfortunately I don't think there's anything that can be done about these. The results are immediately sent off into a Unity event, picked up by Mirror and decoded - since Mirror uses the length of the `byte[]` to determine the length of the packet payload Ignorance is forced to allocate an array of exactly the correct size every single time. This could be fixed with a trivial patch to Mirror (accepting `ArraySegment<byte>` instead of `byte[]` in their event handlers) but I don't think they're likely to merge such a patch.

**Comment by martindevans** [comment]
When do you plan to release Ignorance 1.2? I might release the Dissonance+Mirror+Ignorance update within the next couple of days, or I might delay it a bit if Ignorance will be soon :)

**Pull request merged**
